name: Update README with Results

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run curl command
        run: |
          result=$(curl -X 'GET' \
            'https://datacomp.opensky-network.org/api/rankings' \
            -H 'accept: application/json' | jq)
          echo "$result" > result.txt

      - name: Replace content between placeholders
        run: |
          # Read the result into a variable
          result=$(cat result.txt)
          
          # Use sed to replace the content between the placeholders
          sed -i '/<!--result-start-->/,/<!--result-end-->/c\<!--result-start-->\n'"$result"'\n<!--result-end-->' README.md

      - name: Clean up temporary files
        run: |
          rm result.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use your PAT for authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest leaderboard data'
          git push
